service: stag

frameworkVersion: '2'

custom:
  tableName: stag-table
  bucketName: stag-bucket
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
    migration:
      dir: offline/migrations
  serverless-offline:
    httpPort: 3001

provider:
  name: aws
  runtime: nodejs12.x
  profile: stagUser
  region: eu-west-3
  environment: 
    tableName: ${self:custom.tableName}  
    bucketName: ${self:custom.bucketName}
    dynamoPort: ${self:custom.dynamodb.start.port}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - s3:PutObject
        - s3:GetObject
        - dynamodb:Query
        - dynamodb:PutItem
        - dynamodb:UpdateItem
      Resource: 
        - arn:aws:s3:::${self:provider.environment.bucketName}/*
        - arn:aws:dynamodb:${self:provider.region}:*:table/${self:provider.environment.tableName}/index/*
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dynamodb-local

package:
  individually: true

functions:
  write:
    handler: lambdas/endpoints/write-db.handler
    events:
      - http:
          path: write-db/{PK}/{SK}
          method: POST
          cors: true
  upload:
    handler: lambdas/endpoints/upload.handler
    events:
      - http:
          path: upload
          method: POST
          cors: true
  get:
    handler: lambdas/endpoints/read-db.handler
    events:
      - http:
          path: read-db/{PK}/{SK}
          method: GET
          cors: true

resources:
  Resources:
    serviceBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    serviceTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
          - AttributeName: SK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH
          - AttributeName: SK
            KeyType: RANGE
        BillingMode: PAY_PER_REQUEST


