service: stag

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: stagUser
  region: eu-west-3

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: stag-2020
      localDir: themes

functions:
  getUser:
    handler: lambdas/getUser.handler
    events: 
      - http:
          path: get-users/{ID}
          method: GET
          cors: true 

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: stag-2020
