service: stag

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: stagUser
  region: eu-west-3

plugins:
  - serverless-s3-sync

custom:
  s3Sync:
    - bucketName: stag-2020
      localDir: themes

functions:
  hello:
    handler: handler.hello

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: stag-2020
