service: stag

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  profile: stagUser
  region: eu-west-3
  environment: 
    tableName: ${self:custom.tableName}  
    bucketName: ${self:custom.bucketName}
  iamRoleStatements:
    - Effect: Allow
      Action: 
        - dynamodb:*
        - s3:*
      Resource: '*'

plugins:
  - serverless-webpack

package:
  individually: true

custom:
  tableName: stag
  bucketName: stag-2020

functions:
  registerShop:
    handler: lambdas/endpoints/registerShop.handler
    events:
      - http:
          path: register-shop/{ID}
          method: POST
          cors: true
  createFile:
    handler: lambdas/endpoints/createFile.handler
    events:
      - http:
          path: create-file/{fileName}
          method: POST
          cors: true
  getShop:
    handler: lambdas/endpoints/getShop.handler
    events:
      - http:
          path: get-shop/{shop}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.bucketName}
    DemoDynamoDbTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.tableName}
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S
          - AttributeName: shop
            AttributeType: S
        KeySchema:
          - AttributeName: ID
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        GlobalSecondaryIndexes:
          - IndexName: shop-index
            KeySchema:
              - AttributeName: shop
                KeyType: HASH
            Projection:
              ProjectionType: ALL

