@hostname = http://localhost:3003/dev

##### Getting style
GET {{hostname}}/s3/test.com

# Writing S3
### POST fake Online REST API
POST {{hostname}}/s3/test.com
Content-Type: application/json

{
    "style": "asddadsas",
    "text": "monthly"
}


